name: Update Install Count Badge

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch install count from PostHog
        env:
          POSTHOG_API_TOKEN: ${{ secrets.POSTHOG_API_TOKEN }}
        run: |
          echo "Fetching install count from PostHog..."

          response=$(curl -s -X POST https://app.posthog.com/api/projects/139712/query/ \
            -H "Authorization: Bearer $POSTHOG_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": {
                "kind": "DataTableNode",
                "source": {
                  "kind": "EventsQuery",
                  "event": "qss_world_install",
                  "select": ["count()"]
                }
              }
            }')

          count=$(echo "$response" | jq '.results[0][0] // 0')
          echo "Install count: $count"

          mkdir -p metrics
          echo "{ \"installs\": $count }" > metrics/install-count.json

      - name: Commit & push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics/install-count.json
          git commit -m "Update install count badge" || echo "No changes"
          git push
